# -*-makefile-*-
#
# type: deep, strictness: gnu

MAINTAINERCLEANFILES = Makefile.in
DISTCLEANFILES = \\\#*\\\# Makefile
CLEANFILES = 
MOSTLYCLEANFILES = *~ *.[aios] *.bak *.ci *.io

EXTRA_DIST = 

LATEX = @LATEX@
DVIPS = @DVIPS@
DVIPDFM = @DVIPDFM@
ENSCRIPTBIN = @ENSCRIPTBIN@
PS2PDF = @PS2PDF@

## FIXME: Your stuff here
